### ISSUE TITLE
Checklist to be done

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/grunt-config#1]
The following are things to be done before 1.0.0 is released:

## generations
- [x] `grunt generate readme` (--test option)
- [x] `grunt generate travis` (--test option)
- [x] `grunt generate wercker` (--test option)
- [x] `grunt generate .gitignore` (no need for test option)

## lint
- [x] `grunt eslint`
- [x] `grunt html-lint` (not sure what to call this yet)
- [x] `grunt css-lint` (not sure what to call this yet)
- [x] `grunt lint-all`

## build
- [x] `grunt compile` (--test option)

## internal
- [x] `grunt test-all`

- [x] code style guidline

All of these should be documented in the Grunfile.js

**Comment by brandonLi8** [comment]
This issue has served its needs. Using #16 as the master checklist. Closing.
