### ISSUE TITLE
1.0.0 Master Checklist

### ISSUE THREAD

**Issue by brandonLi8** [brandonLi8/grunt-config#16]
# Top-level Checklist to be completed for 1.0.0:

## Design
- [ ] Design Document Created (Date: //)

## Implementation
- [x] Repository created
- [x] License added
- [ ] Github Project Roadmap completed (Date: //)
- [ ] Code Reviewer Identified and Completed (Date: //)
- [ ] Verify Credits (Date: //)
- [ ] Published! (Date: //)

## Grunt Config
- [x] `npm` initiated with `package.json`
- [x] GitHub labels added
- [ ] `README.md` generated and updated (Date: //)
- [ ] `.gitignore` generated (Date: //)
- [ ] `travis.yml` generated and updated (Date: //)
- [ ] `.wercker.yml` generated and updated (Date: //)

## Testing
- [ ] Performance acceptable (Date: //)
- [ ] Feature Complete (Date: //)
